### ISSUE TITLE
[ERROR]1.12.2 v1.5.2-19

### ISSUE THREAD

**Issue by gamaleev0071** [Buuz135/Thaumic-JEI#33]
Time: 8/13/18 11:25 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.buuz135.thaumicjei.event.ResearchManager.sync(ResearchManager.java:73)
	at com.buuz135.thaumicjei.event.ResearchManager.onTick(ResearchManager.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_454_ResearchManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.buuz135.thaumicjei.event.ResearchManager.sync(ResearchManager.java:73)
	at com.buuz135.thaumicjei.event.ResearchManager.onTick(ResearchManager.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_454_ResearchManager_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:348)

**Comment by Zarepheth** [comment]
I'm receiving the same error.
The full log is on [paste.ee](https://paste.ee/p/pVz5o)

The error occurred about the same time as Minecraft finished loading a world and was about to render the blocks around my location.

**Comment by wamc2017** [comment]
Little addition, it seems to only happen if jei_1.12.2-4.12.0.214 is installed, it works fine with jei_1.12.2-4.11.1.213.

**Comment by gamaleev0071** [comment]
update mod plz** 
corrent ver. jei
 [R] 4.11.0.212
 [B] 4.12.0.214
