### ISSUE TITLE
Error Railcraft+ThaumicJEI

### ISSUE THREAD

**Issue by kellixon** [Buuz135/Thaumic-JEI#42]
MC 1.12.2. Railcraft 12.0.0-b4 + ThaumicJEI 1.5.5-23. Error in log when loading ThaumicJEI.
Full report - https://gist.github.com/kellixon/385b9dcd1d320550a6389bc6a40c8748 (16956-32064 lines).

**Comment by TheCodedOne** [comment]
Theres no error in that log..

**Comment by kellixon** [comment]
`[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: java.lang.ArrayIndexOutOfBoundsException: 4
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at mods.railcraft.common.util.crafting.ShapedRailcraftRecipe.func_179532_b(ShapedRailcraftRecipe.java:68)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:550)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:514)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:604)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:425)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:179)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:558)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:514)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:604)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:425)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:179)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:143)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.common.lib.InternalMethodHandler.getObjectAspects(InternalMethodHandler.java:86)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.api.aspects.AspectHelper.getObjectAspects(AspectHelper.java:69)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at thaumcraft.api.aspects.AspectList.<init>(AspectList.java:21)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at com.buuz135.thaumicjei.ThaumcraftJEIPlugin.createAspectsFile(ThaumcraftJEIPlugin.java:206)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at com.buuz135.thaumicjei.ThaumcraftJEIPlugin.lambda$register$2(ThaumcraftJEIPlugin.java:129)
[16:34:46] [ThaumicJEI Aspect Cache/INFO] [STDERR]: [thaumcraft.common.lib.crafting.ThaumcraftCraftingManager:generateTagsFromCraftingRecipes:529]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by Azim-Palmer** [comment]
This is consistently happening to me now too with the latest versions of ThaumicJEI and Railcraft on 1.12.2 so I've had to remove ThaumicJEI from my client :(
